### ISSUE TITLE
Error creating graph using apollostudio_graph

### ISSUE THREAD

**Issue by uristernik** [sapher/terraform-provider-apollostudio#26]
For the following resource:
```
resource "apollostudio_graph" "test" {
  id          = "testing123"
  name        = "testing123"
  description = "testing123 backend GraphQL API"
}
```

I am getting 
```
╷
│ Error: Failed to create graph
│ 
│   with apollostudio_graph.test,
│   on apollo.tf line 1, in resource "apollostudio_graph" "test":
│    1: resource "apollostudio_graph" "test" {
│ 
│ Failed to create graph: Message: Exception while fetching data (/newService) : Service already exists, Locations: [{Line:1 Column:66}],
│ Extensions: map[classification:DataFetchingException]
```

I have tried creating a new account but still getting this error. Any ideas?

**Comment by uristernik** [comment]
Around two weeks ago it worked on version 1.2.0, I tried now and it fails both on 1.2.0 and on 1.3.0

**Comment by sapher** [comment]
@uristernik let me check on my side. I was able to recreate your issue. I'll try to fix.

**Comment by sapher** [comment]
It seems like graph id are global, meaning two graphs cannot have the same ID even if they are from different accounts. Also graphs are soft deleted, meaning if you delete one, you will need to wait a bit before recreating it. We don't have the API to hard delete a graph, it would be internal to apollo team.

**Comment by sapher** [comment]
@uristernik I wasn't clear in my documentation here : https://registry.terraform.io/providers/sapher/apollostudio/latest/docs/resources/graph#required I'll update it ;)

**Comment by uristernik** [comment]
Thanks for following up @sapher. Works when I use unique name.
